version: "3.2"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana
    env_file: configuration.env
    container_name: grafana
    links:
      - influxdb
      - prometheus
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - grafana-data:/var/lib/grafana 
      
volumes:
  grafana-data:
    external: true
